# # packages in environment at /home/linux/miniconda3/envs/ID2223:
# #
# # Name                    Version                   Build  Channel
# _libgcc_mutex             0.1                        main  
# _openmp_mutex             5.1                       1_gnu  
# absl-py                   2.0.0                    pypi_0    pypi
# aiofiles                  23.2.1                   pypi_0    pypi
# aiohttp                   3.9.1                    pypi_0    pypi
# aiosignal                 1.3.1                    pypi_0    pypi
# aiostream                 0.5.2                    pypi_0    pypi
# altair                    4.2.2                    pypi_0    pypi
# annotated-types           0.6.0                    pypi_0    pypi
# anyio                     3.7.1                    pypi_0    pypi
# argon2-cffi               23.1.0                   pypi_0    pypi
# argon2-cffi-bindings      21.2.0                   pypi_0    pypi
# arrow                     1.3.0                    pypi_0    pypi
# asgiref                   3.7.2                    pypi_0    pypi
# asttokens                 2.4.1                    pypi_0    pypi
# astunparse                1.6.3                    pypi_0    pypi
# async-lru                 2.0.4                    pypi_0    pypi
# async-timeout             4.0.3                    pypi_0    pypi
# attrs                     23.1.0                   pypi_0    pypi
# avro                      1.11.0                   pypi_0    pypi
# babel                     2.14.0                   pypi_0    pypi
# beautifulsoup4            4.12.2                   pypi_0    pypi
# bleach                    6.1.0                    pypi_0    pypi
# boto3                     1.34.7                   pypi_0    pypi
# botocore                  1.34.7                   pypi_0    pypi
# bzip2                     1.0.8                h7b6447c_0  
# ca-certificates           2023.12.12           h06a4308_0  
# cachetools                5.3.2                    pypi_0    pypi
# certifi                   2023.11.17               pypi_0    pypi
# cffi                      1.16.0                   pypi_0    pypi
# charset-normalizer        3.3.2                    pypi_0    pypi
# click                     8.1.7                    pypi_0    pypi
# cloudpickle               2.0.0                    pypi_0    pypi
# colorama                  0.4.6                    pypi_0    pypi
# comm                      0.2.0                    pypi_0    pypi
# confluent-kafka           2.1.1                    pypi_0    pypi
# contourpy                 1.2.0                    pypi_0    pypi
# cryptography              41.0.7                   pypi_0    pypi
# cssutils                  2.9.0                    pypi_0    pypi
# cycler                    0.12.1                   pypi_0    pypi
# dataclasses               0.6                      pypi_0    pypi
# dataframe-image           0.2.3                    pypi_0    pypi
# debugpy                   1.8.0                    pypi_0    pypi
# decorator                 5.1.1                    pypi_0    pypi
# defusedxml                0.7.1                    pypi_0    pypi
# dm-tree                   0.1.8                    pypi_0    pypi
# easydict                  1.10                     pypi_0    pypi
# entrypoints               0.4                      pypi_0    pypi
# exceptiongroup            1.2.0                    pypi_0    pypi
# executing                 2.0.1                    pypi_0    pypi
# fastapi                   0.106.0                  pypi_0    pypi
# fastavro                  1.8.2                    pypi_0    pypi
# fastjsonschema            2.19.0                   pypi_0    pypi
# ffmpy                     0.3.1                    pypi_0    pypi
# filelock                  3.13.1                   pypi_0    pypi
# flatbuffers               23.5.26                  pypi_0    pypi
# fonttools                 4.47.0                   pypi_0    pypi
# fqdn                      1.5.1                    pypi_0    pypi
# frozenlist                1.4.1                    pypi_0    pypi
# fsspec                    2023.12.2                pypi_0    pypi
# furl                      2.1.3                    pypi_0    pypi
# future                    0.18.3                   pypi_0    pypi
# gast                      0.4.0                    pypi_0    pypi
# google-auth               2.25.2                   pypi_0    pypi
# google-auth-oauthlib      1.0.0                    pypi_0    pypi
# google-pasta              0.2.0                    pypi_0    pypi
# gradio                    4.12.0                   pypi_0    pypi
# gradio-client             0.8.0                    pypi_0    pypi
# great-expectations        0.14.13                  pypi_0    pypi
# greenlet                  3.0.3                    pypi_0    pypi
# grpcio                    1.60.0                   pypi_0    pypi
# grpclib                   0.4.3                    pypi_0    pypi
# h11                       0.14.0                   pypi_0    pypi
# h2                        4.1.0                    pypi_0    pypi
# h5py                      3.10.0                   pypi_0    pypi
# hopsworks                 3.4.3                    pypi_0    pypi
# hpack                     4.0.0                    pypi_0    pypi
# hsfs                      3.4.5                    pypi_0    pypi
# hsml                      3.4.5                    pypi_0    pypi
# html2image                2.0.4.3                  pypi_0    pypi
# httpcore                  1.0.2                    pypi_0    pypi
# httpx                     0.26.0                   pypi_0    pypi
# huggingface-hub           0.20.1                   pypi_0    pypi
# hyperframe                6.0.1                    pypi_0    pypi
# idna                      3.6                      pypi_0    pypi
# imbalanced-learn          0.11.0                   pypi_0    pypi
# importlib-metadata        7.0.1                    pypi_0    pypi
# importlib-resources       6.1.1                    pypi_0    pypi
# iniconfig                 2.0.0                    pypi_0    pypi
# ipykernel                 6.27.1                   pypi_0    pypi
# ipython                   8.19.0                   pypi_0    pypi
# ipywidgets                8.1.1                    pypi_0    pypi
# isoduration               20.11.0                  pypi_0    pypi
# javaobj-py3               0.4.3                    pypi_0    pypi
# jax                       0.4.23                   pypi_0    pypi
# jedi                      0.19.1                   pypi_0    pypi
# jinja2                    3.0.3                    pypi_0    pypi
# jmespath                  1.0.1                    pypi_0    pypi
# joblib                    1.3.2                    pypi_0    pypi
# json5                     0.9.14                   pypi_0    pypi
# jsonpatch                 1.33                     pypi_0    pypi
# jsonpointer               2.4                      pypi_0    pypi
# jsonschema                4.20.0                   pypi_0    pypi
# jsonschema-specifications 2023.12.1                pypi_0    pypi
# jupyter-client            8.6.0                    pypi_0    pypi
# jupyter-core              5.5.1                    pypi_0    pypi
# jupyter-events            0.9.0                    pypi_0    pypi
# jupyter-lsp               2.2.1                    pypi_0    pypi
# jupyter-server            2.12.1                   pypi_0    pypi
# jupyter-server-terminals  0.5.1                    pypi_0    pypi
# jupyterlab                4.0.9                    pypi_0    pypi
# jupyterlab-pygments       0.3.0                    pypi_0    pypi
# jupyterlab-server         2.25.2                   pypi_0    pypi
# jupyterlab-widgets        3.0.9                    pypi_0    pypi
# keras                     2.12.0                   pypi_0    pypi
# kiwisolver                1.4.5                    pypi_0    pypi
# ld_impl_linux-64          2.38                 h1181459_1  
# libclang                  16.0.6                   pypi_0    pypi
# libffi                    3.4.4                h6a678d5_0  
# libgcc-ng                 11.2.0               h1234567_1  
# libgomp                   11.2.0               h1234567_1  
# libstdcxx-ng              11.2.0               h1234567_1  
# libuuid                   1.41.5               h5eee18b_0  
# llvmlite                  0.41.1                   pypi_0    pypi
# lxml                      4.9.4                    pypi_0    pypi
# markdown                  3.5.1                    pypi_0    pypi
# markdown-it-py            3.0.0                    pypi_0    pypi
# markupsafe                2.0.1                    pypi_0    pypi
# matplotlib                3.7.4                    pypi_0    pypi
# matplotlib-inline         0.1.6                    pypi_0    pypi
# mdurl                     0.1.2                    pypi_0    pypi
# mistune                   3.0.2                    pypi_0    pypi
# ml-dtypes                 0.3.1                    pypi_0    pypi
# mock                      5.1.0                    pypi_0    pypi
# modal                     0.56.4376                pypi_0    pypi
# multidict                 6.0.4                    pypi_0    pypi
# nbclient                  0.9.0                    pypi_0    pypi
# nbconvert                 7.13.1                   pypi_0    pypi
# nbformat                  5.9.2                    pypi_0    pypi
# ncurses                   6.4                  h6a678d5_0  
# nest-asyncio              1.5.8                    pypi_0    pypi
# notebook-shim             0.2.3                    pypi_0    pypi
# numba                     0.58.1                   pypi_0    pypi
# numpy                     1.23.5                   pypi_0    pypi
# oauthlib                  3.2.2                    pypi_0    pypi
# openssl                   3.0.12               h7f8727e_0  
# opt-einsum                3.3.0                    pypi_0    pypi
# orderedmultidict          1.0.1                    pypi_0    pypi
# orjson                    3.9.10                   pypi_0    pypi
# overrides                 7.4.0                    pypi_0    pypi
# packaging                 23.2                     pypi_0    pypi
# pandas                    2.0.3                    pypi_0    pypi
# pandocfilters             1.5.0                    pypi_0    pypi
# parso                     0.8.3                    pypi_0    pypi
# pexpect                   4.9.0                    pypi_0    pypi
# pillow                    10.1.0                   pypi_0    pypi
# pip                       23.3.1          py310h06a4308_0  
# platformdirs              4.1.0                    pypi_0    pypi
# pluggy                    1.3.0                    pypi_0    pypi
# pmlb                      1.0.1.post3              pypi_0    pypi
# prometheus-client         0.19.0                   pypi_0    pypi
# prompt-toolkit            3.0.43                   pypi_0    pypi
# protobuf                  4.25.1                   pypi_0    pypi
# psutil                    5.9.7                    pypi_0    pypi
# ptyprocess                0.7.0                    pypi_0    pypi
# pure-eval                 0.2.2                    pypi_0    pypi
# pyarrow                   14.0.2                   pypi_0    pypi
# pyasn1                    0.5.1                    pypi_0    pypi
# pyasn1-modules            0.3.0                    pypi_0    pypi
# pycparser                 2.21                     pypi_0    pypi
# pycryptodomex             3.19.0                   pypi_0    pypi
# pydantic                  2.5.3                    pypi_0    pypi
# pydantic-core             2.14.6                   pypi_0    pypi
# pydub                     0.25.1                   pypi_0    pypi
# pygments                  2.17.2                   pypi_0    pypi
# pyhopshive                0.6.4.1.dev0             pypi_0    pypi
# pyhumps                   1.6.1                    pypi_0    pypi
# pyjks                     20.0.0                   pypi_0    pypi
# pymysql                   1.1.0                    pypi_0    pypi
# pyparsing                 2.4.7                    pypi_0    pypi
# pytest                    7.4.3                    pypi_0    pypi
# python                    3.10.13              h955ad1f_0  
# python-dateutil           2.8.2                    pypi_0    pypi
# python-json-logger        2.0.7                    pypi_0    pypi
# python-multipart          0.0.6                    pypi_0    pypi
# pytz                      2023.3.post1             pypi_0    pypi
# pyyaml                    6.0.1                    pypi_0    pypi
# pyzmq                     25.1.2                   pypi_0    pypi
# readline                  8.2                  h5eee18b_0  
# referencing               0.32.0                   pypi_0    pypi
# requests                  2.31.0                   pypi_0    pypi
# requests-oauthlib         1.3.1                    pypi_0    pypi
# rfc3339-validator         0.1.4                    pypi_0    pypi
# rfc3986-validator         0.1.1                    pypi_0    pypi
# rich                      13.7.0                   pypi_0    pypi
# rpds-py                   0.15.2                   pypi_0    pypi
# rsa                       4.9                      pypi_0    pypi
# ruamel-yaml               0.17.17                  pypi_0    pypi
# s3transfer                0.10.0                   pypi_0    pypi
# scikit-learn              1.3.2                    pypi_0    pypi
# scipy                     1.11.4                   pypi_0    pypi
# seaborn                   0.13.0                   pypi_0    pypi
# semantic-version          2.10.0                   pypi_0    pypi
# send2trash                1.8.2                    pypi_0    pypi
# setuptools                68.2.2          py310h06a4308_0  
# shap                      0.44.0                   pypi_0    pypi
# shellingham               1.5.4                    pypi_0    pypi
# sigtools                  4.0.1                    pypi_0    pypi
# six                       1.16.0                   pypi_0    pypi
# slicer                    0.0.7                    pypi_0    pypi
# sniffio                   1.3.0                    pypi_0    pypi
# soupsieve                 2.5                      pypi_0    pypi
# sqlalchemy                2.0.23                   pypi_0    pypi
# sqlite                    3.41.2               h5eee18b_0  
# stack-data                0.6.3                    pypi_0    pypi
# starlette                 0.27.0                   pypi_0    pypi
# synchronicity             0.5.3                    pypi_0    pypi
# tblib                     3.0.0                    pypi_0    pypi
# tensorboard               2.12.3                   pypi_0    pypi
# tensorboard-data-server   0.7.2                    pypi_0    pypi
# tensorflow                2.12.0                   pypi_0    pypi
# tensorflow-estimator      2.12.0                   pypi_0    pypi
# tensorflow-io-gcs-filesystem 0.35.0                   pypi_0    pypi
# tensorflow-probability    0.19.0                   pypi_0    pypi
# termcolor                 2.4.0                    pypi_0    pypi
# terminado                 0.18.0                   pypi_0    pypi
# threadpoolctl             3.2.0                    pypi_0    pypi
# thrift                    0.16.0                   pypi_0    pypi
# tinycss2                  1.2.1                    pypi_0    pypi
# tk                        8.6.12               h1ccaba5_0  
# toml                      0.10.2                   pypi_0    pypi
# tomli                     2.0.1                    pypi_0    pypi
# tomlkit                   0.12.0                   pypi_0    pypi
# toolz                     0.12.0                   pypi_0    pypi
# tornado                   6.4                      pypi_0    pypi
# tqdm                      4.66.1                   pypi_0    pypi
# traitlets                 5.14.0                   pypi_0    pypi
# twofish                   0.3.0                    pypi_0    pypi
# typeguard                 4.0.1                    pypi_0    pypi
# typer                     0.9.0                    pypi_0    pypi
# types-certifi             2021.10.8.3              pypi_0    pypi
# types-python-dateutil     2.8.19.14                pypi_0    pypi
# types-toml                0.10.8.7                 pypi_0    pypi
# typing-extensions         4.9.0                    pypi_0    pypi
# tzdata                    2023.3                   pypi_0    pypi
# tzlocal                   5.2                      pypi_0    pypi
# uri-template              1.3.0                    pypi_0    pypi
# urllib3                   1.26.18                  pypi_0    pypi
# uvicorn                   0.25.0                   pypi_0    pypi
# watchfiles                0.21.0                   pypi_0    pypi
# wcwidth                   0.2.12                   pypi_0    pypi
# webcolors                 1.13                     pypi_0    pypi
# webencodings              0.5.1                    pypi_0    pypi
# websocket-client          1.7.0                    pypi_0    pypi
# websockets                11.0.3                   pypi_0    pypi
# werkzeug                  2.1.2                    pypi_0    pypi
# wheel                     0.41.2          py310h06a4308_0  
# widgetsnbextension        4.0.9                    pypi_0    pypi
# wrapt                     1.14.1                   pypi_0    pypi
# xz                        5.4.5                h5eee18b_0  
# yarl                      1.9.4                    pypi_0    pypi
# ydata-synthetic           1.3.2                    pypi_0    pypi
# zipp                      3.17.0                   pypi_0    pypi
# zlib                      1.2.13               h5eee18b_0  
name: ID2223_Project
dependencies:
  - python=3.10.13
  - pip
  - pip:
    - numpy=1.23.5
    - pandas=2.0.3
    - hopswork=3.4.3
    - joblib=1.3.2
    - ydata-synthetic=1.3.2
    - modal=0.56.4376
    - scikit-learn=1.3.2
    - seaborn=0.13.0
    - gradio=4.12.0
    - imbalanced-learn=0.11.0
    - ipykernel=6.27.1
    - ipywidgets=8.1.1
    - shap=0.44.0
